#!/bin/bash
HOST="root@127.0.0.1"
REMOTE_ROOT="/data/www/cjjob"
if [[ "upload" == $1 ]];then
    scp `dirname $0`/$2/$3 $HOST:$REMOTE_ROOT/$2/$3
elif [[ 'download' == $1 ]];then
    scp $HOST:$REMOTE_ROOT/$2/$3 `dirname $0`/$2/$3
fi
